development:
  adapter: postgresql
  encoding: unicode
  database: xkcd_api_unofficial_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: xkcd_api_unofficial_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: xkcd_api_unofficial_production
  pool: 5